### ISSUE TITLE
PathORAM impl

### ISSUE THREAD

**Issue by tianxiang999** [InitialDLab/SEAL-ORAM#2]
Dear authors, a small problem in **src/PathORAM.cpp** confused me. As in the constructor, height represents the height of the tree while n_blocks represents the number of leaf nodes, so I wonder if:

        height = (uint32_t)ceil(log2((double)n)) + 1; 
should be: 
 
         height = (uint32_t)ceil(log2((double)n)) - 1; 
and

         for (size_t i = 0; i < n_blocks; ++i) pos_map[i] = Util::rand_int(n_blocks);

should be:
  
         for (size_t i = 0; i < n; ++i) pos_map[i] = Util::rand_int(n_blocks);

**Comment by dongx-psu** [comment]
I think there is no problem here. Take an example when n = 4, the height of the tree should be 3, which matches log_2(4) + 1. While the position map is not an issue since when we are building a path-oram for capacity `n`, we are actually building a path-oram of capacity of its nearest power of 2.

Dong
On 9/5/2018 12:05:40 AM, Alan Shen <notifications@github.com> wrote:
Dear authors, a small problem in src/PathORAM.cpp confused me. As in the constructor, height represents the height of the tree while n_blocks represents the number of leaf nodes, so I wonder if:
height = (uint32_t)ceil(log2((double)n)) + 1;
should be:
height = (uint32_t)ceil(log2((double)n)) - 1;
and
for (size_t i = 0; i < n_blocks; ++i) pos_map[i] = Util::rand_int(n_blocks);
should be:
for (size_t i = 0; i < n; ++i) pos_map[i] = Util::rand_int(n_blocks);

**Comment by tianxiang999** [comment]
But when n = 7, the height of the tree becomes 4,so I guess if you count root node in level 1, ceil function should be floor.

**Comment by dongx-psu** [comment]
Tree heights are iterate through:

for (uint32_t i = 0; i < height; ++i)

When n = 7, leaf level has 8 nodes, which indicates the tree has 4 levels.

Dong
On 9/5/2018 12:44:55 AM, Alan Shen <notifications@github.com> wrote:
But when n = 7, the height of the tree becomes 4,so I guess if you count root node in level 1, ceil function should be floor.

**Comment by tianxiang999** [comment]
Got it. Thank you for your kind reply!
